py/django/mysite/mysite/urls.py
#!/usr/bin/python
#-*- Encoding: utf-8 -*-
"""mysite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls', namespace = "polls")),
    url(r'^polls_generic/', include('polls.urls_generic', namespace = "polls_generic")),
    url(r'^admin/', include(admin.site.urls)),
    # test add app
    url(r'^questions/', include('questions.urls', namespace = 'questions')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

py/django/mysite/polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex : /polls/
    url(r'^$', views.index, name = "index"),
    # ex : /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name = 'detail'),
    # ex : /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name = 'results'),
    # ex : /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name = 'vote'),
]

py/django/mysite/questions/urls.py
#!/usr/bin/python
#-*- Encoding: utf-8 -*-
from django.conf.urls import url
from . import views

urlpatterns = [
    # 登录
    url(r'^user_login/$', views.user_login, name = "user_login"),
    url(r'^user_logout/$', views.user_logout, name = "user_logout"),
    
    # 首页
    url(r'^paper/$', views.paper_index, name = "paper_index"),
    # 新建一个paper
    url(r'^paper/new/$', views.paper_new, name = 'paper_new'),
    # paper详细
    url(r'^paper/(?P<paper_id>[0-9]+)/$', views.paper_detail, name = 'paper_detail'),
    # paper结果
    #url(r'^paper/(?P<paper_id>[0-9]+)/result/$', views.paper_result, name = 'paper_result'),

    # question内容 !! pqr_id 不是question_id
    url(r'^question/(?P<pqr_id>[0-9]+)/$', views.question_detail, name = 'question_detail'),
    # question结果
    url(r'^question/(?P<pqr_id>[0-9]+)/result/$', views.question_result, name = 'question_result'),

    # test url
    url(r'^test/$', views.test, name = 'question_test'),
    url(r'^test_markdown/$', views.test_markdown, name = 'question_test_markdown'),
]

py/django/mysite/polls/models.py
#!/usr/bin/python
#-*- Encoding: utf-8 -*-
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length = 200)
    pub_date = models.DateTimeField('date published')

    def __unicode__(self):
        """ 
        __str__ or __unicode__?

        On Python 3, it’s easy, just use __str__().

        On Python 2, you should define __unicode__() methods returning unicode values instead. Django models have a default __str__() method that calls __unicode__() and converts the result to a UTF-8 bytestring. This means that unicode(p) will return a Unicode string, and str(p) will return a bytestring, with characters encoded as UTF-8. Python does the opposite: object has a __unicode__ method that calls __str__ and interprets the result as an ASCII bytestring. This difference can create confusion.

        If all of this is gibberish to you, just use Python 3.
        """
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now >= self.pub_date >= now - datetime.timedelta(minutes = 5)

    # 为了admin 界面后台显示 tips [Writing your first Django app, part 2]
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = "最近发布?"

class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length = 200)
    votes = models.IntegerField(default = 0)

    def __unicode__(self):
        return self.choice_text

py/django/mysite/polls/views.py
#!/usr/bin/python
#-*- Encoding: utf-8 -*-
from django.shortcuts import render

from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader

from django.http import Http404
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse

from .models import Question, Choice

def hello_world(request):
    return HttpResponse("Hello world,index")

def index_old_v1(request):
    """ 
        可以用 render 简化
    """
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    template = loader.get_template('polls/index.html')
    context = RequestContext(request, {
        'latest_question_list' : latest_question_list,
    })
    return HttpResponse(template.render(context))

def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {'latest_question_list' : latest_question_list}
    return render(request, 'polls/index.html', context)

def detail_old_v1(request, question_id):
    """
        可以用 get_object_or_404 简化
    """
    try:
        question = Question.objects.get(pk = question_id)
    except:
        raise Http404("question does not exist")
    return render(request, 'polls/detail.html', {"question" : question})

def detail(request, question_id):
    question = get_object_or_404(Question, pk = question_id)
    return render(request, 'polls/detail.html', {"question" : question})


def results(request, question_id):
    question = get_object_or_404(Question, pk = question_id)
    return render(request, 'polls/results.html', {'question' : question})

def vote(request, question_id):
    p = get_object_or_404(Question, pk = question_id)
    try:
        selected_choice = p.choice_set.get(pk = request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {'question' : p, "error_message":"you didn't select a choice"})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # args = (p.id) # 这样会报错
        return HttpResponseRedirect(reverse('polls:results', args = (p.id,)))

""" ---------- Use generic views --------- 
    Writing your first Django app, part 4
"""
from django.views import generic
class IndexView(generic.ListView):
    template_name = 'polls/question_list.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    # By default, the DetailView generic view uses a template called <app name>/<model name>_detail.html. 
    # Similarly, the ListView generic view uses a default template called <app name>/<model name>_list.html; 
    # 所以注释掉 也会去找这个模板
    #template_name = 'polls/question_detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/question_results.html'

""" def vote 用的还是之前的方法，所以跳转不到polls_generic """

py/django/mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }}</li>
    {% endfor %}
</ul>

py/django/mysite/polls/templates/polls/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}" />
<!--
    % load staticfiles % loads the % static % template tag from the staticfiles template library. 
    The % static % template tag generates the absolute URL of the static file. 
-->

{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <li>
        <!-- <a href="/polls/{{ question.id }}/">{{ question.question_text }}</a> -->
        <!-- polls:detail polls是命名空间，detail 是注册的url name-->
        <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
        </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

py/django/mysite/polls/templates/polls/question_detail.html
<h1>{{ question.question_text }}</h1>
<h2>generic</h2>
{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'polls_generic:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <!-- forloop.counter indicates how many times the for tag has gone through its loop -->
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
    {% endfor %}
    <input type="submit" value="Vote" />
</form>

py/django/mysite/polls/templates/polls/question_list.html
<h2>generic</h2>
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <li>
        <!-- <a href="/polls_generic/{{ question.id }}/">{{ question.question_text }}</a> -->
        <!-- polls_generic:detail polls是命名空间，detail 是注册的url name-->
        <a href="{% url 'polls_generic:detail' question.id %}">{{ question.question_text }}</a>
        </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

py/django/mysite/polls/templates/polls/question_results.html
<h1>{{ question.question_text }}</h1>
<h2>generic</h2>
<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls_generic:detail' question.id %}">Vote again?</a>

py/django/mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>