py/django/mysite/mysite/urls.py
#!/usr/bin/python
#-*- Encoding: utf-8 -*-
"""mysite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls', namespace = "polls")),
    url(r'^polls_generic/', include('polls.urls_generic', namespace = "polls_generic")),
    url(r'^admin/', include(admin.site.urls)),
    # test add app
    url(r'^questions/', include('questions.urls', namespace = 'questions')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

py/django/mysite/polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex : /polls/
    url(r'^$', views.index, name = "index"),
    # ex : /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name = 'detail'),
    # ex : /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name = 'results'),
    # ex : /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name = 'vote'),
]

py/django/mysite/questions/urls.py
#!/usr/bin/python
#-*- Encoding: utf-8 -*-
from django.conf.urls import url
from . import views

urlpatterns = [
    # 登录
    url(r'^user_login/$', views.user_login, name = "user_login"),
    url(r'^user_logout/$', views.user_logout, name = "user_logout"),
    
    # 首页
    url(r'^paper/$', views.paper_index, name = "paper_index"),
    # 新建一个paper
    url(r'^paper/new/$', views.paper_new, name = 'paper_new'),
    # paper详细
    url(r'^paper/(?P<paper_id>[0-9]+)/$', views.paper_detail, name = 'paper_detail'),
    # paper结果
    #url(r'^paper/(?P<paper_id>[0-9]+)/result/$', views.paper_result, name = 'paper_result'),

    # question内容 !! pqr_id 不是question_id
    url(r'^question/(?P<pqr_id>[0-9]+)/$', views.question_detail, name = 'question_detail'),
    # question结果
    url(r'^question/(?P<pqr_id>[0-9]+)/result/$', views.question_result, name = 'question_result'),

    # test url
    url(r'^test/$', views.test, name = 'question_test'),
    url(r'^test_markdown/$', views.test_markdown, name = 'question_test_markdown'),
]

py/django/mysite/questions/models.py
#!/usr/bin/python
#-*- Encoding: utf-8 -*-
import datetime

from django.db import models
from django.utils import timezone

class QuestionUser(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField("用户名", max_length = 50) 
    email = models.EmailField("邮箱")
    create_time = models.DateTimeField('创建时间', auto_now_add = True)
    update_time = models.DateTimeField('更新时间', auto_now = True)

    def __unicode__(self):
        return "<QuestionUser: %s, %s>" % (self.id, self.name)

class Question(models.Model):
    Q_TYPE_SIZES = (
        ("SC" , "单选题"),
        ("MC" , "多选题"),
        ("SA" , "简答题"),
    )
    id = models.AutoField(primary_key=True)
    type = models.CharField("题目类型", max_length = 5, choices = Q_TYPE_SIZES) # q.get_type_display()
    title = models.CharField('题目标题', max_length = 250)
    problem = models.TextField("题目", default = "")
    answer = models.CharField("答案", max_length = 250, default = "")
    create_time = models.DateTimeField('创建时间', auto_now_add = True)
    update_time = models.DateTimeField('更新时间', auto_now = True)

    def __unicode__(self):
        return "<Question: %s>" % self.title

class Paper(models.Model):
    id = models.AutoField(primary_key = True)
    title = models.CharField("试卷标题", max_length = 250, default = "TEST (%s)" % datetime.date.today())
    questions = models.ManyToManyField(Question, 
        through = 'PaperQuestionRelation',
        through_fields = ('paper', 'question'), # tuple元素顺序重要
        related_name = 'papers' # tips 1
    )
    user = models.ForeignKey(QuestionUser, 
        related_name = "papers",
        related_query_name = "paper", # tips 2
    )
    create_time = models.DateTimeField('创建时间', auto_now_add = True)
    update_time = models.DateTimeField('更新时间', auto_now = True)
    
    def __unicode__(self):
        return "<Paper: %s, %s>" % (self.user.name, self.id)

class PaperQuestionRelation(models.Model):
    paper = models.ForeignKey(Paper, related_name = "question_relations")
    question = models.ForeignKey(Question, related_name = 'paper_relations')
    seq_num = models.IntegerField("题目序号")
    user_answer = models.CharField("答案", max_length = 500)
    score = models.IntegerField("得分")
    create_time = models.DateTimeField('创建时间', auto_now_add = True)
    update_time = models.DateTimeField('更新时间', auto_now = True)

    def __unicode__(self):
        return "<PaperQuestionRelation: %s, %s>" % (self.paper.id, self.question.id)

py/django/mysite/questions/models/BaseModel.py
#!/usr/bin/python
#-*- Encoding: utf-8 -*-
import datetime
from django.db import models

class BaseModel(models.Model):
    id = models.AutoField(primary_key=True)
    create_time = models.DateTimeField('创建时间', auto_now_add = True)
    update_time = models.DateTimeField('更新时间', auto_now = True)

    def __unicode__(self):
        return "<%s: %s>" % (self.__class__.__name__, self.id)
    
    class Meta:
        abstract = True

py/django/mysite/questions/models/Paper.py
#!/usr/bin/python
#-*- Encoding: utf-8 -*-

from django.db import models

from BaseModel import *
from Question import *
from PaperUser import *

P_STATUS_SIZE = (
    ('DOING','正在答题'),
    ('GRADING','简答题待评分'),
    ('DONE','已答完'),
    ('CANCAL','作废'),
)

P_TYPE_SIZES = (
    ("ALL" , "默认全部"),
    ("RANDOM" , "随机出题"),
)
class PaperTemplate(BaseModel):
    title = models.CharField(u"试卷模板标题", max_length = 250, default = "TEMPLATE (%s)" % datetime.date.today())
    questions = models.ManyToManyField(Question, 
        related_name = 'paper_templates'
    )
    #questions = models.ManyToManyField(Question)
    type = models.CharField(u"出题方式", max_length = 10, choices = P_TYPE_SIZES, default = "ALL")
    conf_sc = models.IntegerField(u"单选题随机数目", default = 0)
    conf_mc = models.IntegerField(u"多选题随机数目", default = 0)
    conf_sa = models.IntegerField(u"简答题随机数目", default = 0)
    
    def __unicode__(self):
        return "<Paper: %s>" % self.title


class Paper(BaseModel):
    title = models.CharField("试卷标题", max_length = 250, default = "TEST (%s)" % datetime.date.today())
    questions = models.ManyToManyField(Question, 
        through = 'PaperQuestionRelation',
        through_fields = ('paper', 'question'), # tuple元素顺序重要
        related_name = 'papers' # tips 1
    )
    user = models.ForeignKey(PaperUser, 
        related_name = "papers",
        related_query_name = "paper", # tips 2
    )
    status = models.CharField("试卷状态", max_length = 10, choices = P_STATUS_SIZE, default = "DOING") 
    template = models.ForeignKey(PaperTemplate, related_name = "papers", null = True, blank = True)
    
    def __unicode__(self):
        return "<Paper: %s, %s>" % (self.user.name, self.title)
        

py/django/mysite/questions/models/PaperQuestionRelation.py
#!/usr/bin/python
#-*- Encoding: utf-8 -*-

from django.db import models

from BaseModel import *
from Question import *
from Paper import *

class PaperQuestionRelation(BaseModel):
    paper = models.ForeignKey(Paper, related_name = "question_relations")
    question = models.ForeignKey(Question, related_name = 'paper_relations')
    seq_num = models.IntegerField("题目序号")
    user_answer = models.CharField("答案", max_length = 500, blank = True, default = "")
    score = models.IntegerField("得分", default = -1) # -1 表示此题目还没有做

    def arround_question(self):
        """
            依赖 每个paper中seq_num都是递增，不可重复的
            return : (前一道题, 后一道题)
        """
        next_pqrs = PaperQuestionRelation.objects.filter(seq_num = self.seq_num + 1).filter(paper__id = self.paper.id)
        prev_pqrs = PaperQuestionRelation.objects.filter(seq_num = self.seq_num - 1).filter(paper__id = self.paper.id)
        n = next_pqrs[0] if next_pqrs else None
        p = prev_pqrs[0] if prev_pqrs else None
        return (p, n)
        
    def __unicode__(self):
        return "<PaperQuestionRelation: %s, %s>" % (self.paper.id, self.question.id)

py/django/mysite/questions/models/PaperUser.py
#!/usr/bin/python
#-*- Encoding: utf-8 -*-

from django.db import models

from BaseModel import *

class PaperUser(BaseModel):
    name = models.CharField("用户名", max_length = 50) 
    email = models.EmailField("邮箱")

    def __unicode__(self):
        return "<PaperUser: %s, %s>" % (self.id, self.name)

py/django/mysite/questions/models/QuestionPic.py
#!/usr/bin/python
#-*- Encoding: utf-8 -*-

from django.db import models

from BaseModel import *
from Question import *

class QuestionPic(BaseModel):
    question = models.ForeignKey(Question, related_name = "question_pics")
    # failed : 
    #pic = models.ImageField(upload_to = 'QuestionPic/%Y/%m/%d', storage = fs)
    pic = models.ImageField(upload_to = 'questions/QuestionPic/%Y/%m/%d', blank = True)

    def __unicode__(self):
        if self.pic:
            tag = self.pic.path
        else:
            tag = self.id
        return "<QuestionPic: %s>" % tag

py/django/mysite/questions/views.py
#!/usr/bin/python
#-*- Encoding: utf-8 -*-
import random
import datetime

from django.shortcuts import render, render_to_response, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template import RequestContext
from django.views.decorators.csrf import csrf_protect

from .models import *

@csrf_protect
def user_login(request):
    """
        POST : 登录操作
        GET : 返回登录界面
    """
    if request.method == 'POST':
        # todo LDAP check user
        # XXX(login_email, pwd)
        login_email = 'wxyahoo@gmail.com'
        if True:
            u_queryset = PaperUser.objects.filter(email = login_email)
            if u_queryset:
                # 已经登录过
                user = u_queryset[0]
            else:
                # 创建新用户
                user = PaperUser(name = name, email = login_email)
                user.save()
            # question user id
            request.session['q_u_id'] = user.id
            return redirect('questions:paper_index')
        else:
            return render(request, 'questions/user_login.html', {'error_msg': "帐号/密码错误"})
    else:
        return render(request, 'questions/user_login.html', {'error_msg': "请登录"})

def user_logout(request):
    """ 注销登录 """
    try:
        del request.session['q_u_id']
    except KeyError:
        pass
    return redirect('questions:user_login')

def get_random_queryset(queryset, count):
    """ 返回查询结果中 随机的几个 """
    result = []
    tmp_range = range(queryset.count())
    random.shuffle(tmp_range)
    for i in tmp_range[:count]:
        result.append(queryset[i])
    return result
    
def paper_new(request):
    """ 
        用户新创建一个paper 
        根据选择的模板， 随机/完全 两种模式创建 paper
    """
    ptmpl_id = request.GET.get('ptmpl', 1)
    ptmpl = PaperTemplate.objects.get(pk = ptmpl_id)
    q_u_id = request.session['q_u_id']
    u = PaperUser.objects.get(pk = q_u_id)
    p = Paper(
        title = "%s_%s" % (ptmpl.title, datetime.datetime.now().strftime('%H:%M')), 
        status = "DOING", template = ptmpl, user = u
    )
    p.save()
    q_list = []
    if ptmpl.type == 'ALL':
        q_list = Question.objects.filter(paper_templates__id = ptmpl_id).order_by("type")
    elif ptmpl.type == "RANDOM":
        sc_q = Question.objects.filter(paper_templates__id = ptmpl_id).filter(type = "01SC")
        # 返回 单选结果集 中的 配置个数的题目
        q_list = q_list + get_random_queryset(sc_q, ptmpl.conf_sc)
        mc_q = Question.objects.filter(paper_templates__id = ptmpl_id).filter(type = "02MC")
        q_list = q_list + get_random_queryset(mc_q, ptmpl.conf_mc)
        sa_q = Question.objects.filter(paper_templates__id = ptmpl_id).filter(type = "03SA")
        q_list = q_list + get_random_queryset(sa_q, ptmpl.conf_sa)
    # 生产
    pqr_list = []
    for i, q in enumerate(q_list, 1):
        pqr_list.append(PaperQuestionRelation(paper = p, question = q, seq_num = i))
    PaperQuestionRelation.objects.bulk_create(pqr_list)
    #return HttpResponse("paper %s" % p.id)
    return redirect('questions:paper_detail', p.id)

def paper_index(request):
    """ 
        根据用户, 显示所有的paper 
        url : ^paper/$
    """
    paper_templates = PaperTemplate.objects.all()
    # todo 权限
    q_u_id = request.session['q_u_id'] 
    paper_list = Paper.objects.filter(user__id = q_u_id).order_by("-update_time")
    paginator = Paginator(paper_list,10)
    
    page = request.GET.get('page', 1)
    try:
        papers = paginator.page(page)
    except PageNotAnInteger:
        papers = paginator.page(1)
    except EmptyPage:
        papers = paginator.page(paginator.num_pages)
    return render_to_response('questions/paper_index.html', {'papers': papers, "paper_templates": paper_templates})
    
@csrf_protect
def paper_detail(request, paper_id):
    """ 
        根据paper号 显示所有的questions 
        url : ^paper/(?P<paper_id>[0-9]+)/$
    """
    #question_list = Question.objects.filter(paper_relations__id = paper_id)
    pqr_list = PaperQuestionRelation.objects.filter(paper__id = paper_id).order_by("seq_num")
    if request.method == 'POST':
        # post 交卷操作
        # 未作答的题目也更新为0分
        pqr_list.filter(score = -1).update(score = 0)
        paper = Paper.objects.get(pk = paper_id)
        sa_questions = Question.objects.filter(papers__id = paper_id).filter(type = '03SA')
        if sa_questions:
            # 存在简答题，更改为 批改中 状态
            paper.status = "GRADING"
        else:
            paper.status = "DONE"
        paper.save()
        
        return render(request, 'questions/question_list.html', 
            {'pqrs': pqr_list, 'paper_id': paper_id}
        )
    else:
        # 显示所有的questions
        return render(request, 'questions/question_list.html', 
            {'pqrs': pqr_list, 'paper_id': paper_id}
        )
    
#def paper_result(request, paper_id):
#    return HttpResponse(paper_id)

@csrf_protect   
def question_detail(request, pqr_id):
    """ 
        显示具体question内容 
        POST : 提交答案
        GET : 显示问题
        url : ^question/(?P<pqr_id>[0-9]+)/$
    """
    pqr = PaperQuestionRelation.objects.get(pk = pqr_id)
    prev_pqr, next_pqr = pqr.arround_question()
    this_q = pqr.question
    if request.method == 'POST':
        # post请求
        form = this_q.get_answerform(request.POST)
        if form.is_valid(): # tips 需要先is_valid 后 cleaned_data
            answer = form.cleaned_data['answer']
        score, user_answer = this_q.check_answer(answer)
        pqr.score = score
        pqr.user_answer = user_answer
        pqr.save()
        if next_pqr:
            return redirect('questions:question_detail', next_pqr.id)
        else:
            return redirect('questions:paper_detail', pqr.paper.id)
    else:
        # get请求
        form = this_q.get_answerform()
        import markdown2
        return render(request, 'questions/question_detail.html', 
            {
                'pqr': pqr, 
                'next_pqr' : next_pqr,
                'prev_pqr' : prev_pqr,
                'form': form,
                "question_content": markdown2.markdown(this_q.problem)
            }
        )
    
def question_result(request, pqr_id):
    """ 
        显示具体question答案 
        url : ^question/(?P<pqr_id>[0-9]+)/result/$
    """
    pqr = PaperQuestionRelation.objects.get(pk = pqr_id)
    if pqr.paper.status != "DOING":
        # 只有不是 正在答题的 问卷才可以查看答案
        prev_pqr, next_pqr = pqr.arround_question()
        form = pqr.question.get_answerform()
        import markdown2
        return render(request, 'questions/question_result.html', 
            {
                'pqr': pqr, 
                'next_pqr' : next_pqr,
                'prev_pqr' : prev_pqr,
                'form': form,
                "question_content": markdown2.markdown(pqr.question.problem)
            }
        )
    else:
        return HttpResponse("请交卷后再查看答案")


# -------------------------------- 
def test_question_detail(request, pqr_id):
    """ 
       question_detail 测试，不同方式实现 CSRF # tips
    """
    import markdown2
    pqr = PaperQuestionRelation.objects.get(pk = pqr_id)
    return render_to_response('questions/question_detail.html', 
            {'pqr': pqr, "question_content": markdown2.markdown(pqr.question.problem)},
            context_instance=RequestContext(request)
        )
        
def test_markdown(request):
    import markdown2
    q = Question.objects.get(pk = 1)
    print q.problem
    return render_to_response('questions/markdown_test.html', 
            {"my_content": markdown2.markdown(q.problem)}
        )

def test(request):
    return HttpResponse("hello")

py/django/mysite/questions/templates/questions/base.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.4-dist/css/bootstrap.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.4-dist/css/bootstrap-theme.min.css' %}" />
        <script charset="utf-8" src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'questions/css/style.css' %}" />
        {% block css_js %}{% endblock %}
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">问卷系统</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'questions:paper_index' %}">试卷列表 <span class="sr-only">(current)</span></a></li>
                <!--
                <li><a href="#">Link</a></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                    <li class="divider"></li>
                    <li><a href="#">One more separated link</a></li>
                  </ul>
                </li> -->
              </ul>
              <ul class="nav navbar-nav navbar-right">
                  <li><a href="{% url 'questions:user_logout' %}">登出</a></li>
              </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
        <div class = 'container'>
            {% block content %}
            {% endblock %}
            
            {% block footer %}
            <hr>
            <p>footer</p>
            {% endblock %}
        </div>
    </body>
</html>

py/django/mysite/questions/templates/questions/markdown_test.html
{% extends 'questions/base.html' %}
{% load staticfiles %}
{% block css_js %}
    <link rel="stylesheet" type="text/css" href="{% static 'questions/css/style.css' %}" />
{% endblock %}
{% block title %} TEST title {% endblock %}
{% block content %}
    <!-- 信任html输出 -->
    {% autoescape off %}
        {{ my_content }}
    {% endautoescape %}
{% endblock %}

py/django/mysite/questions/templates/questions/paper_index.html
{% extends 'questions/base.html' %}
{% load staticfiles %}

{% block content %}
    {% if papers %}
        <div class = 'row'>
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <h1>已参与试卷:</h1>
                <table class = 'table'>
                    <tr><th class = 'center'>试卷</th><th>状态</th></tr>
                    {% for paper in papers %}
                    <tr>
                        <td class = 'center'><a href="{% url 'questions:paper_detail' paper.id %}">{{ paper.title }}</a></td>
                        <td>{{ paper.get_status_display }}</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
            <div class="col-md-2"></div>
        </div>
    {% endif %}
    <div class = 'row'>
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <h1>新的试卷:</h1>
            <table class = 'table'>
                <tr><th class = 'center'>试卷</th></tr>
                {% for ptmpl in paper_templates %}
                <tr>
                    <td class = 'center'><a href="{% url 'questions:paper_new' %}?ptmpl={{ ptmpl.id }}">{{ ptmpl.title }}</a></td>
                </tr>
                {% endfor %}
            </table>
        </div>
         <div class="col-md-2"></div>
     </div>
{% endblock %}

py/django/mysite/questions/templates/questions/question_detail.html
{% extends 'questions/base.html' %}
{% load staticfiles %}
{% block css_js %}
    <script>
        var user_answer = "{{ pqr.user_answer }}";
        $(document).ready(function () {
            // 简答题
            $('#id_answer').val(user_answer);
            // 多选题
            $("input[type='checkbox']").each(
                function(){
                    if(user_answer.indexOf(this.value) >= 0){
                        $(this).attr("checked",true);
                    }
                }
            );
            // 单选题
            $("input[type='radio']").each(
                function(){
                    if(user_answer.indexOf(this.value) >= 0){
                        $(this).attr("checked",true);
                    }
                }
            );
        });
    </script>
{% endblock %}
{% block title %} TEST title {% endblock %}
{% block content %}
    <!-- 信任html输出 -->
    <h1>{{ pqr.seq_num }} : </h1>
    {% autoescape off %}
        {{ question_content }}
    {% endautoescape %}
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <form action="{% url 'questions:question_detail' pqr.id %}" method="post">
                {% csrf_token %}
                    {% for field in form %}
                        {% for radio in field %}
                            <div>{{ radio }}</div><br/>
                        {% endfor %}
                    {% endfor %}
                    {% comment %}
                    {{ form.as_table }}
                    {% endcomment %}
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
        </div>
        <div class="col-md-4"></div>
    </div>
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <ul class="pagination">
                {% if prev_pqr %}
                    <li><a href="{% url 'questions:question_detail' prev_pqr.id %}">&laquo;</a></li>
                    <li><a href="{% url 'questions:question_detail' prev_pqr.id %}">{{ prev_pqr.seq_num }}</a></li>
                {% endif %}
                <li><a href="{% url 'questions:question_detail' pqr.id %}">{{ pqr.seq_num }}</a></li>
                {% if next_pqr %}
                    <li><a href="{% url 'questions:question_detail' next_pqr.id %}">{{ next_pqr.seq_num }}</a></li>
                    <li><a href="{% url 'questions:question_detail' next_pqr.id %}">&raquo;</a></li>
                {% endif %}
                
            </ul>
        </div>
        <div class="col-md-4"></div>
    </div>
{% endblock %}

py/django/mysite/questions/templates/questions/question_result.html
{% extends 'questions/base.html' %}
{% load staticfiles %}
{% block css_js %}
    <link rel="stylesheet" type="text/css" href="{% static 'questions/css/style.css' %}" />
    <script>
        var user_answer = "{{ pqr.user_answer }}";
        $(document).ready(function () {
            // 简答题
            $('#id_answer').val(user_answer);
            // 多选题
            $("input[type='checkbox']").each(
                function(){
                    if(user_answer.indexOf(this.value) >= 0){
                        $(this).attr("checked",true);
                    }
                }
            );
            // 单选题
            $("input[type='radio']").each(
                function(){
                    if(user_answer.indexOf(this.value) >= 0){
                        $(this).attr("checked",true);
                    }
                }
            );
        });
    </script>
{% endblock %}
{% block title %} TEST 答案 {% endblock %}
{% block content %}
    <!-- 信任html输出 -->
    <h1>{{ pqr.seq_num }} : </h1>
    {% autoescape off %}
        {{ question_content }}
    {% endautoescape %}
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <h3 class = 'green'>正确答案 : {{ pqr.question.answer }}</h3>
        </div>
        <div class="col-md-4"></div>
    </div>
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <h3>您的答案:</h3>
            <form action="#" method="post">
                {% csrf_token %}
                {% for field in form %}
                    {% for radio in field %}
                        <div>{{ radio }}</div><br/>
                    {% endfor %}
                {% endfor %}
                {% comment %}
                {{ form.as_table }}
                {% endcomment %}
            </form>
        </div>
        <div class="col-md-4"></div>
    </div>
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <ul class="pagination">
                {% if prev_pqr %}
                    <li><a href="{% url 'questions:question_result' prev_pqr.id %}">&laquo;</a></li>
                    <li><a href="{% url 'questions:question_result' prev_pqr.id %}">{{ prev_pqr.seq_num }}</a></li>
                {% endif %}
                <li><a href="{% url 'questions:question_result' pqr.id %}">{{ pqr.seq_num }}</a></li>
                {% if next_pqr %}
                    <li><a href="{% url 'questions:question_result' next_pqr.id %}">{{ next_pqr.seq_num }}</a></li>
                    <li><a href="{% url 'questions:question_result' next_pqr.id %}">&raquo;</a></li>
                {% endif %}
            </ul>
        </div>
        <div class="col-md-4"></div>
    </div>
{% endblock %}

py/django/mysite/questions/templates/questions/user_login.html
{% extends 'questions/base.html' %}
{% load staticfiles %}
{% block title %} TEST 登录 {% endblock %}
{% block content %}
    <form action = "{% url 'questions:user_login' %}" method = "post">
        {% csrf_token %}
        <input class = '' name = 'email' type="email" class="form-control" id="u_email" placeholder="some@sohu-inc.com"></input>
        <input class = '' name = 'password' type="password"></input>
        <button type="submit" class="btn btn-default">Login</button>
    </form>
{% endblock %}